# vim: set tabstop=2 shiftwidth=2 expandtab softtabstop=2 autoindent smartindent:
# http://eslint.org/docs/rules

# Copied from js/.eslintrc.yaml

rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      # TODO: allow or require on functions once parser supports
      functions: never
  no-extra-boolean-cast:
    - off
  no-console:
    - off
  no-constant-condition:
    - error
    - checkLoops: false
  no-debugger:
    - off
  block-scoped-var:
    - error
  keyword-spacing:
    - warn
  no-trailing-spaces:
    - error
  quotes:
    - warn
    - single
    # TODO: enable template literals once we implement them
    - allowTemplateLiterals: false
      avoidEscape: true
  no-duplicate-imports:
    - error
  max-len:
    - error
    - code:       80
      ignoreUrls: true
  no-tabs:
    - error
  no-mixed-spaces-and-tabs:
    - off # just say no to tabs

  # Because of Reach's different scoping rules,
  # we can't use the undef/unused warnings
  no-undef:
    - off
  no-unused-vars:
    - off
  # Disabling this lets you use _ for multiple ignored args
  no-redeclare:
    - off
  # TODO: enable this once we fix anti-examples/partial_loop_var_updates.rsh
  no-self-assign:
    - off


env:
  es6:      true
  node:     true
  browser:  true

globals:
  baseDir: true
  _: true

extends:
  - 'eslint:recommended'

parserOptions:
  sourceType:  module
  ecmaVersion: 10

parser: babel-eslint
