name:                reach
version:             0.1.0
github:              "reach-sh/reach-lang"
license:             Apache-2.0
author:              "Reach"
maintainer:          "jay@reach.sh"
copyright:           "2019 Reach"
description:         Please visit the GitHub repository <https://github.com/reach-sh/reach-lang#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- base64
- bytestring
- containers
- cryptonite
- deepseq
- digest
- directory
- extra
- file-embed >= 0.0.9
- filepath
- generic-deriving
- haskell-evm
- hexstring
- hspec
- hspec-smallcheck
- language-javascript >= 0.7.1.0
- lattices
- loop
- memory
- mtl
- optparse-applicative
- parsec-numbers
- pretty-simple
- prettyprinter
- process
- safe
- silently
- simple-smt
- smallcheck
- system-filepath
- tasty
- tasty-ant-xml
- tasty-golden
- tasty-hspec
- tasty-html
- text
- unordered-containers

default-extensions:
- BangPatterns
- DeriveAnyClass
- DeriveDataTypeable
- DeriveGeneric
- EmptyDataDeriving
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StrictData
- TemplateHaskell
- TypeApplications
- TypeSynonymInstances

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -O2
- -fwrite-ide-info
- -hiedir=.hie

library:
  source-dirs: src

executables:
  reachc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reach

tests:
  reach-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reach
