name:                reach
version:             0.1.0.0
github:              "Reach-sh/reach-lang"
license:             LGPL-2.1
author:              "Reach"
maintainer:          "jay@reach.sh"
copyright:           "2019 Reach"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/Reach-sh/reach-lang#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- prettyprinter
- megaparsec
- parser-combinators
- bytestring
- mtl
- filepath
- directory
- file-embed >= 0.0.9
- process
- pretty-simple
- text
- debug
- extra
- simple-smt
- aeson
- unordered-containers
- optparse-applicative
- system-filepath
- digest
- language-javascript >= 0.6.0.13
- parsec-numbers

ghc-options:
- -Wall
- -Werror
- -O2

library:
  source-dirs: src

executables:
  reachc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reach

tests:
  reach-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reach
