version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  shellcheck: circleci/shellcheck@2.0.0
  jq: circleci/jq@2.2.0
jobs:
  build-and-test:
    docker:
      - image: reachsh/reach-circle:0.1.2
    steps:
      - checkout
      - run:
          name: install mo
          command: (curl -sSL https://git.io/get-mo -o mo && chmod +x mo && mv mo /usr/local/bin)
      - run:
          name: hs package.yaml
          command: (cd hs && make package.yaml)
      - restore_cache:
          keys:
            - hs-2-{{ checksum "hs/stack.yaml" }}-{{ checksum "hs/package.yaml" }}
            - hs-2-{{ checksum "hs/stack.yaml" }}
            - hs-2-
            - hs-
      - run:
          name: install hs dependencies
          command: (cd hs && make hs-deps)
      - save_cache:
          key: hs-2-{{ checksum "hs/stack.yaml" }}-{{ checksum "hs/package.yaml" }}
          paths:
            - /root/.stack
            - hs/.stack_work
      - run:
          name: clean hs
          command: (cd hs && make hs-clean)
      - run:
          name: build hs
          command: (cd hs && make hs-build)
      # TODO: split test/check hs and dockerized stuff
      # into separate jobs that reuse the hs build
      - run:
          name: test hs (xml)
          command: (cd hs && make hs-test-xml)
      - store_test_results:
          path: hs/test-reports
      - run:
          name: check hs
          command: (cd hs && make hs-check)
      - store_artifacts:
          path: hs/stan.html
      - setup_remote_docker
      - run:
          name: build ethereum-devnet
          command: (cd scripts/ethereum-devnet && make build)
      # TODO: cache node_modules?
      - run:
          name: build and test js
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            nvm install 12.18.3
            nvm use 12.18.3
            (cd js && make package.json && npm install)
            (cd js && make build test)
      - run:
          name: rebuild examples
          command: (cd examples && make clean-all build-all)
      - run:
          name: run examples
          command: (cd examples && make run-all)
          no_output_timeout: 1m
      - jq/install
      - run:
          name: Is dockerhub up to date?
          command: scripts/docker-check.sh || echo 'XXX allowed to fail'
      - slack/status:
          fail_only: true

  docs-render:
    # TODO: simpler docker image for docs
    docker:
      - image: reachsh/reach-circle:0.1.2
    steps:
      - checkout
      - run:
          name: install pygments-reach
          command: (cd py && make install)
      - run:
          name: render docs
          command: (cd docs-src && make render)
      - store_artifacts:
          path: docs/
      - run:
          name: copy docs to workspace
          command: |
            mkdir -p /tmp/docs_workspace
            cp -r docs /tmp/docs_workspace/
      - persist_to_workspace:
          root: /tmp/docs_workspace
          paths:
            - docs
      - slack/status:
          fail_only: true

  docs-deploy:
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/docs_workspace
      - run:
          name: Install and configure dependencies
          # gh-pages@3.0.0, not 3.1.0, because:
          # https://github.com/tschaub/gh-pages/issues/354#issuecomment-647801438
          command: |
            # sudo npm install -g --silent gh-pages@3.0.0
            git config user.email "ci-build@reach.sh"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "b5:65:6d:49:4f:fb:c1:77:2c:13:45:b1:d9:f9:71:c6"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            git fetch origin gh-pages
            git checkout gh-pages
            git pull origin gh-pages
            git rm -r .
            cp -r /tmp/docs_workspace/docs/* .
            git add .
            # https://stackoverflow.com/questions/8123674/how-to-git-commit-nothing-without-an-error
            git diff-index --quiet HEAD || git commit -m "[ci skip] docs for $CIRCLE_SHA1"
            git push origin gh-pages
      - slack/status:
          fail_only: true

  shellcheck:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - shellcheck/install
      - run:
          name: Run shellcheck
          command: make sh-lint
      - slack/status:
          fail_only: true

  reach-lint:
    docker:
      - image: 'circleci/node:12.18.3'
    steps:
      - checkout
      - run:
          name: install mo
          command: (curl -sSL https://git.io/get-mo -o mo && chmod +x mo && sudo mv mo /usr/local/bin)
      - run:
          name: package.json
          command: (cd js && make package.json)
      - run:
          name: install eslint
          command: (cd js && sudo npm install -g eslint && npm install)
      - run:
          name: Run reach linter
          command: make reach-lint
      - slack/status:
          fail_only: true

  docker-lint:
    docker:
      - image: 'hadolint/hadolint:v1.18.0-6-ga0d655d-alpine'
    steps:
      - checkout
      - run:
          name: install make and bash
          command: apk add make bash
      - run:
          name: run hadolint
          command: make docker-lint
      - slack/status:
          fail_only: true

  experimental-algorand-devnet:
    docker:
      - image: reachsh/reach-circle:v0.1.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build algorand-devnet
          command: (cd scripts/algorand-devnet && make build)
      - run:
          name: check algorand-devnet
          command: |
            cd scripts/algorand-devnet
            make run &
            sleep 1
            make status
            cd -
          # TODO: a better test, proper wait
      - slack/status:
          fail_only: true

workflows:
  build-and-test:
    jobs:
      - build-and-test

  docs:
    jobs:
      - docs-render
      - docs-deploy:
          requires:
            - docs-render
          filters:
            branches:
              only: master
  lint:
    jobs:
      - shellcheck
      - reach-lint
      - docker-lint
  # TODO: re-enable / integrate with build-and-test
  # experimental-devnets:
  #   jobs:
  #     - experimental-algorand-devnet
