version: 2.1
orbs:
  jq: "circleci/jq@2.2.0"
  shellcheck: "circleci/shellcheck@2.2.0"
  slack: "circleci/slack@4.3.3"

executors:
  fake:
    parameters:
      class:
        description: "resource class"
        default: "small"
        type: string
    docker:
    - image: "cimg/base:stable"
      auth:
        username: $DOCKER_LOGIN
        password: $DOCKER_PASSWORD
    resource_class: <<parameters.class>>
    environment:
      LC_ALL: "en_US.UTF-8"
  real:
    machine:
      image: "ubuntu-2004:202107-02"
    resource_class: "medium"
    environment:
      LC_ALL: "en_US.UTF-8"
      PATH: "/home/circleci/.local/bin:/usr/local/bin:/usr/bin:/bin:/sbin"

commands:
  workattach:
    steps:
      - attach_workspace:
          at: /tmp/workspace
  slack_fail:
    steps:
      - slack/notify:
          # NOTE: We used to do
          # branch_pattern: "master,gh-pages"
          # But, I am disabling it on purpose
          event: fail
          # XXX make circle_branch a link
          custom: |
            { "blocks": [
                { "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*FAIL* ${CIRCLE_USERNAME}/${CIRCLE_BRANCH} > ${CIRCLE_JOB} <${CIRCLE_BUILD_URL}|more...>" }}]}
  srd_yes:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: '20.10.6'
  srd_no:
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
          version: '20.10.6'
  restore_bin:
    description: "Restore the build binaries"
    steps:
      - workattach
      - run: |
          mkdir -p ~/.local
          ln -sf /tmp/workspace/bin ~/.local/bin
          ls ~/.local/bin/*
  and_restore_docker:
    parameters:
      images:
        description: "which connector"
        type: string
    description: "Restore the build Docker images"
    steps:
      - run: |
          source ./VERSION

          for IMG in <<parameters.images>>; do
            zcat /tmp/workspace/docker-${IMG}/${IMG}.tar.gz | docker load
            docker tag reachsh/${IMG}:latest reachsh/${IMG}:${VERSION}
            docker tag reachsh/${IMG}:latest reachsh/${IMG}:${MAJOR}.${MINOR}
            docker tag reachsh/${IMG}:latest reachsh/${IMG}:${MAJOR}
          done
jobs:
  "deploy":
    executor: real
    steps:
    - checkout
    - attach_workspace:
        at: /tmp/workspace
    - and_restore_docker
    - run: |
        docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
        for IMG in runner rpc-server reach reach-cli devnet-algo devnet-eth devnet-cfx; do
          ./scripts/docker-push.sh reachsh/${IMG}
        done 
  "docs-render":
    executor: fake
    steps:
    - checkout
    - run: |
        sudo add-apt-repository -y ppa:plt/racket \
            && sudo apt update \
            && sudo apt install -y --no-install-recommends \
              libcairo2 \
              libfontconfig1 \
              libjpeg62 \
              libpangocairo-1.0-0 \
              racket \
              python3-setuptools
        (cd pygments && sudo make install)
        (cd docs-src && make render)
        mkdir -p /tmp/workspace/
        cp -fr docs /tmp/workspace/
    - persist_to_workspace:
        root: /tmp/workspace/
        paths:
          - docs
    - slack_fail
  "docs-deploy":
    executor: fake
    steps:
    - checkout
    - workattach
    - add_ssh_keys:
        fingerprints:
        - "83:23:9c:21:6a:74:61:48:20:da:a3:45:79:89:3e:86"
    - run: |
        git config user.email "devbot@reach.sh"
        git config user.name "reachdevbot"
        git fetch origin gh-pages
        git checkout gh-pages
        git pull origin gh-pages
        git rm -r .
        cp -r /tmp/workspace/docs/* .
        [ -f index.html ] || exit 1
        git add .
        # https://stackoverflow.com/questions/8123674/how-to-git-commit-nothing-without-an-error
        git diff-index --quiet HEAD || (git commit -m "[ci skip] docs for ${CIRCLE_SHA1}" && touch .did_change)
        git push origin gh-pages
    - slack_fail
    - run: |
        if [ -f .did_change ]; then
          git diff --exit-code HEAD~ guide-changelog.html
        fi
    - slack/notify:
        event: fail
        channel: 'CMY2TF38D' # general
        # (CMY3E5B3J = reach-lang)
        custom: |
          {
            "blocks": [{
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "<https://docs.reach.sh/guide-changelog.html|Changelog> has changed!"
              }
            }]
          }

  "sh-check":
    executor: fake
    steps:
    - checkout
    - shellcheck/install
    - run: |
        make sh-lint
    - slack_fail
  "build-devnet-cfx":
    executor:
      name: fake
      class: "medium"
    steps:
    - checkout
    - srd_yes
    - run: |
        mkdir -p /tmp/workspace/docker-devnet-cfx
        (cd scripts/devnet-cfx && make build)
        echo "docker save reachsh/devnet-cfx:latest..."
        docker save reachsh/devnet-cfx:latest | gzip > /tmp/workspace/docker-devnet-cfx/devnet-cfx.tar.gz
    - persist_to_workspace:
        root: /tmp/workspace/
        paths:
          - docker-devnet-cfx
  "build-devnet-algo":
    executor:
      name: fake
      class: "medium"
    steps:
    - checkout
    - srd_yes
    - run: |
        mkdir -p /tmp/workspace/docker-devnet-algo
        (cd scripts/devnet-algo && make build)
        echo "docker save reachsh/devnet-algo:latest..."
        docker save reachsh/devnet-algo:latest | gzip > /tmp/workspace/docker-devnet-algo/devnet-algo.tar.gz
    - persist_to_workspace:
        root: /tmp/workspace/
        paths:
          - docker-devnet-algo
  "build-devnet-eth":
    executor:
      name: fake
      class: "medium"
    steps:
    - checkout
    - srd_yes
    - run: |
        mkdir -p /tmp/workspace/docker-devnet-eth
        (cd scripts/devnet-eth && make build)
        echo "docker save reachsh/devnet-eth:latest..."
        docker save reachsh/devnet-eth:latest | gzip > /tmp/workspace/docker-devnet-eth/devnet-eth.tar.gz
    - persist_to_workspace:
        root: /tmp/workspace/
        paths:
          - docker-devnet-eth
  "build-haskell":
    executor:
      name: fake
      class: "medium"
    steps:
    - checkout
    - srd_yes
    - run: |
        mkdir -p /tmp/workspace/docker-haskell-build-artifacts
        (cd hs && make build-haskell)
        echo "docker save reachsh/haskell-build-artifacts:latest..."
        docker save reachsh/haskell-build-artifacts:latest | gzip > /tmp/workspace/docker-haskell-build-artifacts/haskell-build-artifacts.tar.gz
    - persist_to_workspace:
        root: /tmp/workspace/
        paths:
          - bin
          - docker-haskell-build-artifacts
    - slack_fail
  "build-reach":
    executor:
      name: fake
      class: "medium"
    steps:
    - checkout
    - srd_yes
    - attach_workspace:
        at: /tmp/workspace
    - and_restore_docker:
        images: "haskell-build-artifacts"
    - run: |
        mkdir -p /tmp/workspace/docker-reach
        (cd hs && make build-reachc)
        echo "docker save reachsh/reach:latest..."
        docker save reachsh/reach:latest | gzip > /tmp/workspace/docker-reach/reach.tar.gz
    - persist_to_workspace:
        root: /tmp/workspace/
        paths:
          - bin
          - docker-reach
    - slack_fail   
  "build-reach-cli":
    executor:
      name: fake
      class: "medium"
    steps:
    - checkout
    - srd_yes
    - attach_workspace:
        at: /tmp/workspace
    - and_restore_docker:
        images: "haskell-build-artifacts"
    - run: |
        mkdir -p /tmp/workspace/docker-reach-cli
        (cd hs && make build-reach-cli)
        echo "docker save reachsh/reach-cli:latest..."
        docker save reachsh/reach-cli:latest | gzip > /tmp/workspace/docker-reach-cli/reach-cli.tar.gz
    - persist_to_workspace:
        root: /tmp/workspace/
        paths:
          - bin
          - docker-reach-cli
    - slack_fail
  "build-js-deps":
    executor:
      name: fake
      class: "medium"
    steps:
    - checkout
    - srd_yes
    - run: |
        mkdir -p /tmp/workspace/docker-js-deps
        (cd js && make build-js-deps)
        echo "docker save reachsh/js-deps:latest..."
        docker save reachsh/js-deps:latest | gzip > /tmp/workspace/docker-js-deps/js-deps.tar.gz
    - persist_to_workspace:
        root: /tmp/workspace/
        paths:
          - bin
          - docker-js-deps
    - slack_fail
  "build-stdlib":
    executor:
      name: fake
      class: "medium"
    steps:
    - checkout
    - srd_yes
    - attach_workspace:
        at: /tmp/workspace
    - and_restore_docker:
        images: "haskell-build-artifacts js-deps"
    - run: |
        mkdir -p /tmp/workspace/docker-stdlib
        (cd js && make build-stdlib)
        echo "docker save reachsh/stdlib:latest..."
        docker save reachsh/stdlib:latest | gzip > /tmp/workspace/docker-stdlib/stdlib.tar.gz
    - persist_to_workspace:
        root: /tmp/workspace/
        paths:
          - bin
          - docker-stdlib
    - slack_fail
  "build-runner":
    executor:
      name: fake
      class: "medium"
    steps:
    - checkout
    - srd_yes
    - attach_workspace:
        at: /tmp/workspace
    - and_restore_docker:
        images: "stdlib"
    - run: |
        mkdir -p /tmp/workspace/docker-runner
        (cd js && make build-runner)
        echo "docker save reachsh/runner:latest..."
        docker save reachsh/runner:latest | gzip > /tmp/workspace/docker-runner/runner.tar.gz
    - persist_to_workspace:
        root: /tmp/workspace/
        paths:
          - bin
          - docker-runner
    - slack_fail
  "build-rpc-server":
    executor:
      name: fake
      class: "medium"
    steps:
    - checkout
    - srd_yes
    - attach_workspace:
        at: /tmp/workspace
    - and_restore_docker:
        images: "runner"
    - run: |
        mkdir -p /tmp/workspace/docker-rpc-server
        (cd js && make build-rpc-server)
        echo "docker save reachsh/rpc-server:latest..."
        docker save reachsh/rpc-server:latest | gzip > /tmp/workspace/docker-rpc-server/rpc-server.tar.gz
    - persist_to_workspace:
        root: /tmp/workspace/
        paths:
          - bin
          - docker-rpc-server
    - slack_fail
  "build-react-runner":
    executor:
      name: fake
      class: "medium"
    steps:
    - checkout
    - srd_yes
    - attach_workspace:
        at: /tmp/workspace
    - and_restore_docker:
        images: "js-deps stdlib"
    - run: |
        mkdir -p /tmp/workspace/docker-react-runner
        (cd js && make build-react-runner)
        echo "docker save reachsh/react-runner:latest..."
        docker save reachsh/react-runner:latest | gzip > /tmp/workspace/docker-react-runner/react-runner.tar.gz
    - persist_to_workspace:
        root: /tmp/workspace/
        paths:
          - bin
          - docker-react-runner
    - slack_fail
  "hs-test":
    executor: real
    steps:
    - attach_workspace:
        at: /tmp/workspace/
    - checkout
    - and_restore_docker:
        images: "haskell-build-artifacts"
    - run: |
        mkdir -p hs/test-reports
        docker run -v $(pwd)/examples:/examples/ -v $(pwd)/docs-src:/docs-src/ -v $(pwd)/hs/test-reports:/test-reports -ti reachsh/haskell-build-artifacts stack test --fast --test-arguments --xml=/test-reports/junit.xml
    - store_test_results:
        path: "hs/test-reports"
    - slack_fail
  "hs-check":
    executor:
      name: fake
      class: "medium"
    steps:
    - checkout
    - attach_workspace:
        at: /tmp/workspace
    - srd_yes
    - and_restore_docker
    - run: |
        docker run -ti reachsh/haskell-build-artifacts /bin/sh -c 'stack build stan ; stack exec stan report'
    - store_artifacts:
        path: hs/stan.html
    - slack_fail
  "examples":
    parameters:
      connector:
        description: "which connector"
        type: string
      size:
        description: "parallel size"
        type: string
      rank:
        description: "parallel rank"
        type: string
    executor: real
    steps:
    - checkout
    - attach_workspace:
        at: /tmp/workspace/
    - and_restore_docker
    - run: |
        mkdir -p /tmp/workspace/artifacts /tmp/workspace/record /tmp/artifacts
    - run:
        command: |
          cd .circleci && ./example.sh <<parameters.connector>> <<parameters.size>> <<parameters.rank>>
        no_output_timeout: 20m
    - store_artifacts:
        path: /tmp/artifacts
    - run: |
        CIRCLE_ARTIFACTS_URL=$(curl -X GET "https://circleci.com/api/v2/project/github/reach-sh/reach-lang/${CIRCLE_BUILD_NUM}/artifacts" \
          -H "Accept: application/json" \
          -u "${CIRCLE_API_TOKEN}:")
        echo "${CIRCLE_ARTIFACTS_URL}" > /tmp/workspace/artifacts/<<parameters.connector>>.<<parameters.rank>>
    - persist_to_workspace:
        root: /tmp/workspace
        paths:
          - artifacts
          - record
  "examples-sink":
    executor: fake
    steps:
    - checkout
    - workattach
    - run: |
        ./.circleci/record.py >> $BASH_ENV
    - run:
        when: always
        command: |
          echo "${RECORD_MESSAGE}"
    - slack/notify:
        event: always
        # NOTE: We used to do
        # branch_pattern: "master,gh-pages"
        # But, I am disabling it on purpose
        custom: |
          { "blocks": [
              { "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${RECORD_MESSAGE}" }}]}
workflows:
  docs:
    jobs:
    - "docs-render":
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
    - "docs-deploy":
       filters:
         branches:
           only: master
       requires:
       - "docs-render"
  buildless:
    jobs:
    - "sh-check":
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
  build:
    jobs:
    - "build-devnet-algo":
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
    - "build-devnet-eth":
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
    - "build-devnet-cfx":
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
    - "build-haskell":
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
    - "build-reach":
        requires:
          - "build-haskell"
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
    - "build-reach-cli":
        requires:
          - "build-haskell"
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
    - "build-js-deps":
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
    - "build-stdlib":
        requires:
          - "build-haskell"
          - "build-js-deps"
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
    - "build-runner":
        requires:
          - "build-stdlib"
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
    - "build-react-runner":
        requires:
          - "build-stdlib"
          - "build-js-deps"
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
    - "build-rpc-server":
        requires:
          - "build-runner"
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
    - "hs-test":
        requires:
          - "build-haskell"
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
    - "hs-check":
        requires:
          - "build-haskell"
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
    - hold:
        requires:
          - "build-devnet-algo"
          - "build-devnet-eth"
          - "build-devnet-cfx"
          - "build-haskell"
          - "build-reach"
          - "build-reach-cli"
          - "build-js-deps"
          - "build-stdlib"
          - "build-runner"
          - "build-react-runner"
          - "build-rpc-server"
          - "hs-test"
          - "hs-check"
        type: approval
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
          branches:
            ignore: /.*/
    - "deploy":
        context:
        - reachdevbot-on-dockerhub
        requires:
          - "hold"
        filters:
          tags:
            only: /[0-9]*\.[0-9]*\.[0-9]*/
          branches:
            ignore: /.*/
    # Sink and examples follow
