version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build-and-test:
    docker:
      - image: fpco/stack-build:lts-16.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - hs-{{ checksum "hs/stack.yaml" }}-{{ checksum "hs/package.yaml" }}
            - hs-{{ checksum "hs/stack.yaml" }}
            - hs-
      - run:
          name: install hs dependencies
          command: (cd hs && stack build --dependencies-only)
      - run:
          name: install hs test dependencies
          command: (cd hs && stack test --dependencies-only)
      - save_cache:
          key: hs-{{ checksum "hs/stack.yaml" }}-{{ checksum "hs/package.yaml" }}
          paths:
            - /root/.stack
            - hs/.stack_work
      - run:
          name: build hs
          command: (cd hs && stack build)
      - run:
          name: test hs
          command: (cd hs && stack test || echo allowed to fail)
      - slack/status

workflows:
  build-and-test:
    jobs:
      - build-and-test
