version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build-and-test:
    docker:
      - image: danburton/reach-circle:v0.1.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - hs-{{ checksum "hs/stack.yaml" }}-{{ checksum "hs/package.yaml" }}
            - hs-{{ checksum "hs/stack.yaml" }}
            - hs-
      - run:
          name: install hs dependencies
          command: (cd hs && stack build --dependencies-only)
      - run:
          name: install hs test dependencies
          command: (cd hs && stack test --dependencies-only)
      - save_cache:
          key: hs-{{ checksum "hs/stack.yaml" }}-{{ checksum "hs/package.yaml" }}
          paths:
            - /root/.stack
            - hs/.stack_work
      - run:
          name: build hs
          command: (cd hs && stack build)
      - run:
          name: test hs
          command: (cd hs && stack test || echo allowed to fail)
      - run:
          name: build js
          command: (cd js && make build)
      - run:
          name: build ethereum-devnet
          command: (cd scripts/ethereum-devnet && make build)
      - run:
          name: rebuild examples
          command: (cd examples && make clean-all build-all)
      - run:
          name: run examples
          command: (cd examples && make run-all)
          no_output_timeout: 1m
      - slack/status:
          fail_only: true

workflows:
  build-and-test:
    jobs:
      - build-and-test
