version: '3'
services:
  reach-app:
    image: reachsh/examples-rps:v0.1.1
    depends_on:
      - devnet
    environment:
      - ETH_NODE_URI=http://devnet:8545
      - ALGO_SERVER=http://docker.for.mac.localhost
  devnet:
    image: reachsh/ethereum-devnet:v0.1.1

