version: '3.4'
x-app-base: &app-base
  image: reachsh/reach-app-tut-7:latest
services:
  devnet:
    image: reachsh/ethereum-devnet:latest
  reach-app-tut-7-ETH-test-dockerized-geth: &default-app
    <<: *app-base
    depends_on:
      - devnet
    environment:
      - REACH_CONNECTOR_MODE=ETH-test-dockerized-geth
      - ETH_NODE_URI=http://devnet:8545
  reach-app-tut-7-ETH-test-embedded-ganache:
    <<: *app-base
    environment:
      - REACH_CONNECTOR_MODE=ETH-test-embedded-ganache
  reach-app-tut-7-FAKE-test-embedded-mock:
    <<: *app-base
    environment:
      - REACH_CONNECTOR_MODE=FAKE-test-embedded-mock
  reach-app-tut-7-: *default-app
  reach-app-tut-7: *default-app
  # After this is new!
  live:
    <<: *app-base
    environment:
      - ETH_NODE_URI
  player: &player
    <<: *default-app
    stdin_open: true
  alice: *player 
  bob: *player 
